name: stay_away_from_me
description: Project for BeaverHacks Fall 2020.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.7.2  
  shared_preferences: ^0.5.8
  cupertino_icons: ^0.1.3
  google_fonts: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  liquid_progress_indicator: ^0.3.2
  vibrate: ^0.0.4
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
    image_path: "assets/images/safmpng.png"
    android: true
    ios: true

flutter:
  uses-material-design: true
  fonts:
   - family: LexendPeta
     fonts:
      - asset: assets/fonts/LexendPeta-Regular.ttf

  assets:
    - assets/images/safmpng.png
  